### ISSUE TITLE
If providing spec.resources cpu but not memory then memory is set incorrectly  

### ISSUE THREAD

**Issue by alex-glv** [ContainerSolutions/redis-operator#58]
If resource req/limits are not set, the operator will calculate memory automatically by taking redis.conf maxmemory value and adding 300mb, the cpu value is not set.

However, if we wish to set the cpu (let memory limits be inferred from redis.conf maxmemory field) the memory is not then calculated, but is set to 100mb (the default)
```
  resources:
    limits:
      cpu: 1
    requests:
      cpu: 1
```

Sane defaults and flexible enough configuration should be possible.
